UpdateCTestConfiguration  from :/home/aurelien/dev_ws/src/build/articubot_one/CTestConfiguration.ini
Parse Config file:/home/aurelien/dev_ws/src/build/articubot_one/CTestConfiguration.ini
   Site: dell-ag
   Build name: (empty)
 Add coverage exclude regular expressions.
Create new tag: 20230326-1442 - Experimental
UpdateCTestConfiguration  from :/home/aurelien/dev_ws/src/build/articubot_one/CTestConfiguration.ini
Parse Config file:/home/aurelien/dev_ws/src/build/articubot_one/CTestConfiguration.ini
Test project /home/aurelien/dev_ws/src/build/articubot_one
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: copyright

1: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/copyright.xunit.xml" "--package-name" "articubot_one" "--output-file" "/home/aurelien/dev_ws/src/build/articubot_one/ament_copyright/copyright.txt" "--command" "/opt/ros/humble/bin/ament_copyright" "--xunit-file" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/copyright.xunit.xml"
1: Test timeout computed to be: 200
1: -- run_test.py: invoking following command in '/home/aurelien/dev_ws/src/articubot_one':
1:  - /opt/ros/humble/bin/ament_copyright --xunit-file /home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/copyright.xunit.xml
1: CONTRIBUTING.md: file not found
1: LICENSE: file not found
1: launch/launch_sim.launch.py: could not find copyright notice
1: launch/rsp.launch.py: could not find copyright notice
1: 4 errors, checked 4 files
1: -- run_test.py: return code 1
1: -- run_test.py: verify result file '/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/copyright.xunit.xml'
1/5 Test #1: copyright ........................***Failed    0.21 sec
test 2
    Start 2: flake8

2: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/flake8.xunit.xml" "--package-name" "articubot_one" "--output-file" "/home/aurelien/dev_ws/src/build/articubot_one/ament_flake8/flake8.txt" "--command" "/opt/ros/humble/bin/ament_flake8" "--xunit-file" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/flake8.xunit.xml"
2: Test timeout computed to be: 60
2: -- run_test.py: invoking following command in '/home/aurelien/dev_ws/src/articubot_one':
2:  - /opt/ros/humble/bin/ament_flake8 --xunit-file /home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/flake8.xunit.xml
2:     xacro_file = os.path.join(pkg_path,'description','robot.urdf.xacro')
2:                                       ^
2:     xacro_file = os.path.join(pkg_path,'description','robot.urdf.xacro')
2:                                                     ^
2:     
2: ^
2:     # Launch!
2:     ^
2: def generate_launch_description():
2: ^
2:     # Include the robot_state_publisher launch file, provided by our own package. Force sim time to be enabled
2:     ^
2:     # Include the robot_state_publisher launch file, provided by our own package. Force sim time to be enabled
2:                                                                                                    ^
2:     package_name='articubot_one' #<--- CHANGE ME
2:                 ^
2:     package_name='articubot_one' #<--- CHANGE ME
2:                                 ^
2:     package_name='articubot_one' #<--- CHANGE ME
2:                                  ^
2:                     get_package_share_directory(package_name),'launch','rsp.launch.py'
2:                                                              ^
2:                     get_package_share_directory(package_name),'launch','rsp.launch.py'
2:                                                                       ^
2:     # Run the spawner node from the gazebo_ros package. The entity name doesn't really matter if you only have a single robot.
2:                                                                                                    ^
2:     # Launch them all!
2:     ^
2:     ])      ^
2: 1     E225 missing whitespace around operator
2: 4     E231 missing whitespace after ','
2: 1     E261 at least two spaces before inline comment
2: 1     E262 inline comment should start with '# '
2: 4     E303 too many blank lines (3)
2: 2     E501 line too long (110 > 99 characters)
2: 1     W292 no newline at end of file
2: 1     W293 blank line contains whitespace
2: 
2: ./launch/rsp.launch.py:20:39: E231 missing whitespace after ','
2: 
2: ./launch/rsp.launch.py:20:53: E231 missing whitespace after ','
2: 
2: ./launch/rsp.launch.py:22:1: W293 blank line contains whitespace
2: 
2: ./launch/rsp.launch.py:33:5: E303 too many blank lines (2)
2: 
2: ./launch/launch_sim.launch.py:14:1: E303 too many blank lines (3)
2: 
2: ./launch/launch_sim.launch.py:17:5: E303 too many blank lines (2)
2: 
2: ./launch/launch_sim.launch.py:17:100: E501 line too long (110 > 99 characters)
2: 
2: ./launch/launch_sim.launch.py:20:17: E225 missing whitespace around operator
2: 
2: ./launch/launch_sim.launch.py:20:33: E261 at least two spaces before inline comment
2: 
2: ./launch/launch_sim.launch.py:20:34: E262 inline comment should start with '# '
2: 
2: ./launch/launch_sim.launch.py:24:62: E231 missing whitespace after ','
2: 
2: ./launch/launch_sim.launch.py:24:71: E231 missing whitespace after ','
2: 
2: ./launch/launch_sim.launch.py:34:100: E501 line too long (126 > 99 characters)
2: 
2: ./launch/launch_sim.launch.py:42:5: E303 too many blank lines (3)
2: 
2: ./launch/launch_sim.launch.py:47:7: W292 no newline at end of file
2: 
2: 
2: 2 files checked
2: 15 errors
2: 
2: 'E'-type errors: 13
2: 'W'-type errors: 2
2: 
2: Checked files:
2: 
2: * ./launch/rsp.launch.py
2: * ./launch/launch_sim.launch.py
2: -- run_test.py: return code 1
2: -- run_test.py: verify result file '/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/flake8.xunit.xml'
2/5 Test #2: flake8 ...........................***Failed    0.21 sec
test 3
    Start 3: lint_cmake

3: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/lint_cmake.xunit.xml" "--package-name" "articubot_one" "--output-file" "/home/aurelien/dev_ws/src/build/articubot_one/ament_lint_cmake/lint_cmake.txt" "--command" "/opt/ros/humble/bin/ament_lint_cmake" "--xunit-file" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/lint_cmake.xunit.xml"
3: Test timeout computed to be: 60
3: -- run_test.py: invoking following command in '/home/aurelien/dev_ws/src/articubot_one':
3:  - /opt/ros/humble/bin/ament_lint_cmake --xunit-file /home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/lint_cmake.xunit.xml
3: 
3: No problems found
3: -- run_test.py: return code 0
3: -- run_test.py: verify result file '/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/lint_cmake.xunit.xml'
3/5 Test #3: lint_cmake .......................   Passed    0.11 sec
test 4
    Start 4: pep257

4: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/pep257.xunit.xml" "--package-name" "articubot_one" "--output-file" "/home/aurelien/dev_ws/src/build/articubot_one/ament_pep257/pep257.txt" "--command" "/opt/ros/humble/bin/ament_pep257" "--xunit-file" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/pep257.xunit.xml"
4: Test timeout computed to be: 60
4: -- run_test.py: invoking following command in '/home/aurelien/dev_ws/src/articubot_one':
4:  - /opt/ros/humble/bin/ament_pep257 --xunit-file /home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/pep257.xunit.xml
4: checking ./launch/launch_sim.launch.py
4: checking ./launch/rsp.launch.py
4: No problems found
4: -- run_test.py: return code 0
4: -- run_test.py: verify result file '/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/pep257.xunit.xml'
4/5 Test #4: pep257 ...........................   Passed    0.16 sec
test 5
    Start 5: xmllint

5: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/xmllint.xunit.xml" "--package-name" "articubot_one" "--output-file" "/home/aurelien/dev_ws/src/build/articubot_one/ament_xmllint/xmllint.txt" "--command" "/opt/ros/humble/bin/ament_xmllint" "--xunit-file" "/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/xmllint.xunit.xml"
5: Test timeout computed to be: 60
5: -- run_test.py: invoking following command in '/home/aurelien/dev_ws/src/articubot_one':
5:  - /opt/ros/humble/bin/ament_xmllint --xunit-file /home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/xmllint.xunit.xml
5: File 'package.xml' is invalid:
5: error : Resource temporarily unavailable
5: warning: failed to load external entity "http://download.ros.org/schema/package_format3.xsd"
5: Schemas parser error : Failed to locate the main schema resource at 'http://download.ros.org/schema/package_format3.xsd'.
5: WXS schema http://download.ros.org/schema/package_format3.xsd failed to compile
5: 
5: 1 files are invalid
5: -- run_test.py: return code 1
5: -- run_test.py: verify result file '/home/aurelien/dev_ws/src/build/articubot_one/test_results/articubot_one/xmllint.xunit.xml'
5/5 Test #5: xmllint ..........................***Failed    0.16 sec

40% tests passed[0;0m, [0;31m3 tests failed[0;0m out of 5

Label Time Summary:
copyright     =   0.21 sec*proc (1 test)
flake8        =   0.21 sec*proc (1 test)
lint_cmake    =   0.11 sec*proc (1 test)
linter        =   0.85 sec*proc (5 tests)
pep257        =   0.16 sec*proc (1 test)
xmllint       =   0.16 sec*proc (1 test)

Total Test time (real) =   0.85 sec

The following tests FAILED:
	[0;31m  1 - copyright (Failed)[0;0m
	[0;31m  2 - flake8 (Failed)[0;0m
	[0;31m  5 - xmllint (Failed)[0;0m
Errors while running CTest
Output from these tests are in: /home/aurelien/dev_ws/src/build/articubot_one/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
